
DELETE FROM raipee_municipal;
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('Olvera', 46.50, 0.00, 0.00, 0.80);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('El Puerto de Santa María', 0.00, 0.00, 0.00, 3.70);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('Jimena de la Frontera', 0.00, 18.80, 0.00, 0.10);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('Jerez de la Frontera', 334.90, 0.00, 0.00, 728.80);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('Medina Sidonia', 147.90, 0.00, 0.00, 125.50);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('Puerto Serrano', 0.00, 0.00, 0.00, 125.80);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('Puerto Real', 144.00, 0.00, 0.00, 326.70);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('Alcalá del Valle', 441.00, 0.00, 0.00, 86.50);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('Alcalá de los Gazules', 58.00, 0.00, 0.00, 301.60);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('Barbate', 7.80, 0.00, 0.00, 0.00);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('Arcos de la Frontera', 0.00, 4.60, 0.00, 5.20);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('Algodonales', 0.00, 0.00, 0.00, 2.00);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('Algeciras', 0.00, 0.00, 0.00, 0.90);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('Los Barrios', 61.80, 0.00, 0.00, 4.00);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('Villamartín', 0.00, 0.00, 0.00, 12.30);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('Trebujena', 0.00, 0.00, 0.00, 53.20);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('Setenil de las Bodegas', 0.00, 2.30, 0.00, 1.50);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('Tarifa', 554.90, 0.00, 0.00, 0.00);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('Sanlúcar de Barrameda', 0.00, 0.00, 0.00, 2.40);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('San Roque', 0.00, 0.00, 0.00, 12.30);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('Vejer de la Frontera', 107.90, 0.00, 0.00, 0.00);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('San José del Valle', 0.00, 5.30, 0.00, 268.90);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('Conil de la Frontera', 0.00, 0.00, 0.00, 0.10);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('Chiclana de la Frontera', 23.20, 0.00, 0.00, 0.00);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('Chipiona', 0.00, 0.00, 0.00, 0.10);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('Espera', 38.50, 0.00, 0.00, 1.10);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('Cádiz', 0.00, 0.00, 0.00, 0.80);
INSERT INTO raipee_municipal (municipio_name, mw_eol, mw_hid, mw_biomasa, mw_sol) VALUES ('San Martín del Tesorillo', 67.40, 0.00, 0.00, 0.10);
